gcp/README.md
gcp/instance.tf
gcp/main.tf
gcp/network.tf
gcp/outputs.tf
gcp/variables.tf

This pull request contains code to deploy the ecommerce application to Google Cloud (GCP). It uses the existing `docker-compose` files to start up application containers on a single GCP instance, automatically initialize `goreplay` to generate traffic, and sends metrics to Datadog. The GCP compute instance is accessible by default via a public IP.
Initially created as part of a webinar and requested by @burningion.

Deploy eCommerce to Google Cloud

---

aws/agent-task.json
aws/shop-task.json
store-frontend-broken-instrumented/api/config/initializers/datadog.rb
store-frontend-broken-instrumented/config/initializers/datadog.rb
store-frontend-broken-instrumented/frontend/config/initializers/datadog.rb
store-frontend-instrumented-fixed/config/initializers/datadog.rb
store-frontend-instrumented-fixed/frontend/config/initializers/datadog.rb

This PR fixes hardcoded Agent hostnames in the Docker images for the broken-instrumented and instrumented-fixed directories.
Instead of hardcoding, we can instead set the Agent hostname via the default environment variable, `DD_AGENT_HOST`. This will allow us more flexibility in deploying to diverse environments, such as ECS.
Besides this, it adds an `aws/`  directory, including an example task definition for the Agent Daemon task, and the eCommerce shop. For now, it will only run on ECS on EC2.

Add example ECS task roles and fix hardcoded Agent hostname

---

k8s-manifests/ecommerce-app/frontend.yaml

The "deployment" section of v1, post-beta, has been replaced by "apps". https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
How this affects us: 
In clusters running 1.17 or newer, the old manifest will no longer work, stating that there is no "Deployment" target found in `extensions/v1beta`. This has moved to `v1`, but even changing the version does no address the issues as `deployment` is now under the `apps` umbrella.

Updating Frontend Manifest for 1.17+

---

store-frontend-instrumented-fixed/Dockerfile
store-frontend-instrumented-fixed/docker-entrypoint.sh
store-frontend-instrumented-fixed/store-frontend/Gemfile
store-frontend-instrumented-fixed/store-frontend/app/controllers/application_controller.rb
store-frontend-instrumented-fixed/store-frontend/config/environments/development.rb
store-frontend-instrumented-fixed/store-frontend/config/environments/production.rb
store-frontend-instrumented-fixed/store-frontend/config/initializers/assets.rb
store-frontend-instrumented-fixed/store-frontend/config/initializers/lograge.rb

This spree-commerce rails app was not properly created to begin with so I am applying generous amounts of duct tape and good intentions until we can safely re-build this from scratch in the storedog folder after things calm down.
I centralized the logging configuration into the lograge initializer and tweaked the default development environment to suppress the cache hit debug messages for now which were the original issue from before. The reason this was never running at top-speed to begin with was the docker-entrypoint trying to pass `RAILS_ENV` to the `cd` command and not the rails boot command. Another discovery is that this _only_ uses Sqlite3 for the database and not Postgres, which I discovered when I got it booting in production mode, only to find it was missing the …

Fixup store-frontend-instrumented build and a few other things

---

discounts-service/discounts.py

I want to start a discussion about removing the left-over sleeps from the broken discount service.
It made sense when we didn't have the n+1 query, but with the n+1 query, this is enough to see that something is off in the traces. Actually, the sleep hides a bit the issue.
Removing the sleep, leaves a 1 second span mostly used for several postgres queries, which is more visual in my opinion.

Remove sleeps from broken discounts

---

deploy/README.md
deploy/datadog/helm-values.yaml.example
deploy/generic-k8s/ecommerce-app/advertisements.yaml
deploy/generic-k8s/ecommerce-app/discounts.yaml
deploy/generic-k8s/ecommerce-app/frontend.yaml

This is a follow up to #41 with some more tweaks to the documentation and configurations. It does the following:
* Simplifies the Datadog HELM chart instructions
* Switches back to ClusterIP over LoadBalancer for ingress on the frontend (some k8s flavors out there handle this case differently)
* Uses unified tagging to make the generic-k8s experience better out of the box because not all services were using the same tag which made it difficult to work with in APM

Deploy cleanup

---

store-frontend-broken-no-instrumentation/store-frontend/app/controllers/.#discount_code.rb
store-frontend-instrumented-fixed/store-frontend/app/controllers/.#discount_code.rb

These survived the attempted removal in fb8411bd084864938ee3ea7434fcfc304ef346ed
Without removing these, it creates fun file missing errors when cloning/copying the repo like so:
```bash
$ grep -R -a 'discount_code' .
grep: ./store-frontend-instrumented-fixed/store-frontend/app/controllers/.#discount_code.rb: No such file or directory
grep: ./store-frontend-broken-no-instrumentation/store-frontend/app/controllers/.#discount_code.rb: No such file or directory
```
This must be merged before #49 can be considered

Cleanup broken symlinks

---

.github/workflows/advertisements-fixed.yml
.github/workflows/advertisements.yml

This is my first pass at a Github action that will build and publish the Advertisements service container to the Github Container Registry. For now, it will publish just a latest tag which we currently do to the Docker Hub registry. We can tackle versioning at another time.
I am putting my own access token here for now until they can support organizational level access tokens for publishing to this repo.
Relates to #47

Initial Github Action for Advertisements

---

.github/workflows/advertisements-fixed.yml
.github/workflows/advertisements.yml
ads-service-fixed/Dockerfile
ads-service-fixed/requirements.txt
ads-service/Dockerfile
ads-service/requirements.txt

Similar to #63 this upgrades the Python release to latest stable (3.9) while also upgrading the dependencies. Should help with consistency across services to keep all of the python versions closer together.

Upgrade advertisements services

---

.github/workflows/advertisements-fixed.yml
.github/workflows/advertisements.yml

This is what I get for reading v1 docs instead of the v2 docs and getting confused. Context is really the folder path where the Dockerfile lives. The file key is for the name of the Dockerfile at that directory or if it lives in another directory. To simplify things, we're going with the default behavior as it would be to build via docker locally where you provide the context where the Dockerfile lives and it figures out the rest.

Fix a misunderstanding of context in advertisements publish workflows

---

ads-service-fixed/.dockerignore
ads-service-fixed/Dockerfile
ads-service-fixed/build.sh
ads-service/.dockerignore
ads-service/Dockerfile
ads-service/build.sh

This does a few things:
* Adds a dockerignore to eliminate extra baggage in the resulting docker
image
* Adds a `build.sh` script for more easily reproducable builds. Will
eventually put this into the CI/CD pipeline (and document in README)
* Updates the Dockerfile to use the new BuildKit system in Docker 20.10
which has been out and stable for some time now
* Changes the base image to Debian Buster (Slim) for easier to find and
predictable packages. Alpine can be more problematic with certain
package versions.
Plenty more improvements to come, but this first pass cuts the build
time from about 1 minute 30 seconds down to about 30 seconds with basic
caching. It also cuts the image size down from 525mb to 365mb.
This also _drastically_ speeds up load times (see below) if you run these new …

First pass at optimizing builds for advertisements

---

store-frontend-broken-instrumented/Dockerfile
store-frontend-broken-instrumented/build.sh
store-frontend-broken-instrumented/docker-entrypoint.sh
store-frontend-broken-instrumented/store-frontend/Gemfile
store-frontend-broken-instrumented/store-frontend/Gemfile.lock
store-frontend-instrumented-fixed/Dockerfile
store-frontend-instrumented-fixed/build.sh
store-frontend-instrumented-fixed/docker-entrypoint.sh
store-frontend-instrumented-fixed/store-frontend/Gemfile
store-frontend-instrumented-fixed/store-frontend/Gemfile.lock

This PR is similar to #70 and #67 for optimizing the container builds. I saved the most complex for last of course 😉 
* Cleans up and updates the Dockerfile to upgrade Ruby to 2.7.2 which is the last of the 2.x releases
* Upgrades Bundler to 2.1+ for faster computation of dependencies and installation of them during build/dev time
* Replaces the `build.sh` script with something geared for our project, not theirs
* Replaces the git/directory dependency on Spree and friends to the remote github gem installs which eliminates a lot of startup logging noise that contributes to the issue in #61 and that opens the door to deleting a lot of code and history that doesn't need to be here
* Massively speeds up startup and runtime. First hit will still be the slowest, but once the caching warms up …

Storefront service optimization

---

store-frontend-broken-instrumented/docker-entrypoint.sh
store-frontend-broken-instrumented/store-frontend/config/environments/development.rb
store-frontend-instrumented-fixed/docker-entrypoint.sh
store-frontend-instrumented-fixed/store-frontend/config/environments/development.rb

To temporarily support #61 until we can ship a better solution in #80 this PR tweaks a few things in the store-frontend application to silence a lot of the logging noise. Much of it comes from running Rails in development mode which is designed to be very verbose by default, but lograge itself is just as opinionated as rails and strictly only reformats production logging. This ends up creating extremely noisy logs for a student in training or workshops so we will eventually push to a more production-like setup. However, that is a significant amount of work right now and this gets us a temporary solution to help unblock the training team.

Silence and reformat more logs on the storefront

---

store-frontend-instrumented-fixed/Gemfile.lock

This upgrades the ddtracer library to help track down a potential issue with contexts not being generated in logs.
For ref #110

Upgrade ddtrace on the fixed storefront

---

store-frontend-broken-instrumented/config/environments/development.rb
store-frontend-instrumented-fixed/config/environments/development.rb

This was a difficult bug to track down. The short answer here is that Semantic Logger's Rack logging adapter will either do a call on a Proc within the log tags or a call on any symbol against the incoming Rack request object. It was difficult to understand this subtle difference, but it solved the problem. My big clue was knowing the datadog tracer was always supposed to return some kind of string, not nil.
Fixes #110 once merged.

Resolve Rails app logging issue where traces were not being captured

---

.github/advertisements-errors.yml
ads-service-errors/Dockerfile
ads-service-errors/README.md
ads-service-errors/advertisements.patch

This PR introduces a new `ads-service-errors` image which will inherit from `advertisements-fixed:1.0.0` and patch a regression as to not have large amounts of duplicate code in repository.

Created new ads-errors image with simple regression patch

---

store-frontend-broken-instrumented/config/environments/development.rb
store-frontend-instrumented-fixed/config/environments/development.rb

This is a pattern in the new semantic_logger library where a lot of relevant log facets are being wrapped in a payload key inside the JSON log payload which makes it difficult to parse out of the box. By flattening the payload key back into the main structure we can get the default pipeline to work out of the box for us.
We are going from this:
```json
{
"message": "baz",
"payload": {
"path": "/foo",
"status": 200
}
}
```
To this:
```json
{
"message": "baz",
"path": "/foo",
"status": 200
}
```
Closes #117

Flatten out payload in logs on storefront

---

store-frontend-broken-instrumented/Gemfile
store-frontend-broken-instrumented/Gemfile.lock
store-frontend-instrumented-fixed/Gemfile
store-frontend-instrumented-fixed/Gemfile.lock

This drastically slows down the browser rendering and was a leftover from originally forking the spree project. It is normally intended for use in development mode and not production since it adds to the overall rendering time. It will support @obensource in some upcoming courses around frontend projects.

Remove rack mini profiler

---

deploy/terraform/aws-ec2/main.tf
deploy/terraform/aws-ec2/network.tf
deploy/terraform/aws-ec2/variables.tf

The terraform files already pick a region but the az is random. This was fine in initial testing, but then I changed the region to us-west-2 and it chose us-west-2d and nothing would get created. This pr introduces an az to force it to an az based on the chosen region for the relevant resources.
Signed-off-by: Matt Williams <m@technovangelist.com>

Update to use availability zone where needed

---

.github/workflows/advertisements-errors.yml
.github/workflows/release.yml
CHANGELOG.md
RELEASING.md

This is an effort to speed up the release cycle by automating a lot of the steps I took manually in #102 which reduces 24 steps into 6. I have done as much testing as I can with this workflow and will be getting another look at it before merge.

Automate tagged releases with documentation

---

.github/workflows/advertisements-errors.yml

The ads-error image is just based on a patch for ads-service-fixed, so we need to build it every time ads-service-fixed changes as well, if not we are missing a lot of updates in this image

Build the ads errors image when fixed changes

---

README.md
ads-service-fixed/Dockerfile
ads-service/Dockerfile
deploy/aws/ecs/agent-task.json
deploy/aws/ecs/shop-task.json
deploy/docker-compose/docker-compose-broken-instrumented.yml
deploy/docker-compose/docker-compose-broken-no-apm-instrumentation.yml
deploy/docker-compose/docker-compose-fixed-instrumented-livecode.yml
deploy/docker-compose/docker-compose-fixed-instrumented.yml
deploy/gcp/gke/datadog-agent.yaml
deploy/generic-k8s/cluster-agent/cluster-agent.yaml
deploy/generic-k8s/datadog-agent/datadog-agent.yaml
deploy/generic-k8s/ecommerce-app/advertisements.yaml
deploy/generic-k8s/ecommerce-app/discounts.yaml
deploy/generic-k8s/ecommerce-app/frontend.yaml
deploy/openshift/cluster-agent/cluster-agent.yaml
deploy/openshift/datadog-agent/datadog-agent.yaml
discounts-service-fixed/Dockerfile
discounts-service/Dockerfile
store-frontend-broken-no-instrumentation/api/config/initializers/datadog.rb
store-frontend-broken-no-instrumentation/config/initializers/datadog.rb
store-frontend-broken-no-instrumentation/frontend/config/initializers/datadog.rb

To set the goundwork for #9 this pushes all default environments to `development` instead of `ruby-shop` or `none` (the default if Datadog does not detect an environment) which some of the services were doing.
Part of this issue was due to the optimizations we made in the Docker containers and forgot to use default entrypoints and environment variables to set the `DD_ENV` by default. What this ended up doing was making the out-of-box experience with APM a lot more confusing by having two distinct deployment environments. Having the default entrypoints in the containers also reduces a lot of the repetitive commands in all our separate configurations which makes it more difficult to change later. All of this can be over-ridden via Docker or any of the kubernetes configurations so it will …

Make 'development' the default environment

---

.github/workflows/advertisements-errors.yml
.github/workflows/advertisements-fixed.yml
.github/workflows/advertisements.yml
.github/workflows/discounts-fixed.yml
.github/workflows/discounts.yml
.github/workflows/storefront-fixed.yml
.github/workflows/storefront-no-instrumentation.yml
.github/workflows/storefront.yml
.github/workflows/traffic-replay.yml

Sometimes is useful to be able to trigger manual builds for certain workflows.
This change allows for that

Allow manual build triggers for Github actions workflows

---

deploy/docker-compose/docker-compose-traffic-replay.yml
traffic-replay/Dockerfile

The host and port env vars were not declared in the Dockerfile, and not overrideable.

Make traffic-replay env vars overrideable

---

.github/workflows/release.yml

This should allow us to manually run the release workflow via Github UI

Allow manual trigger of release workflow

---

.github/workflows/release.yml

Running the release workflow manually does not work because it loses reference to the official release tag. I need to hardcode the tag version this one-time, and subsequent new releases should auto-grab the associated tag and work OOTB

Manually add tag to images

---

deploy/docker-compose/docker-compose-broken-no-apm-instrumentation.yml
deploy/docker-compose/docker-compose-broken-no-instrumentation.yml
deploy/docker-compose/docker-compose-fixed-instrumented-attack.yml
store-frontend/docker-entrypoint.sh
store-frontend/storefront-versions/store-frontend-broken-instrumented/Dockerfile
store-frontend/storefront-versions/store-frontend-broken-no-instrumentation/Dockerfile
store-frontend/storefront-versions/store-frontend-instrumented-fixed/Dockerfile

This pull request fixes a problem introduced in 3199fe5725d1f56ee2c24eaf1e43edd411212a27 where patches were added in favor of reducing code duplication.  The docker-compose files formerly leveraged a shared volume with each code set.  Now that the patches are applied to the containers themselves this PR does the following:
Adds an entrypoint outside of the app working directory to `/opt/storedog/`
Removes volume share from the docker-compose itself
Removes explicit command override in favor of letting the container default to the CMD in the Dockerfile

fix docker-compose files for lms

---

deploy/gcp/gke/advertisements.yaml
deploy/gcp/gke/discounts.yaml
deploy/gcp/gke/frontend.yaml

- Bump GKE images to 2.1.2 to use new RUM package with Session Replay #177

Bump to 2.1.2 for RUM and Session Replay

---

deploy/docker-compose/docker-compose-broken-instrumented.yml

This removes a mount pointing to a patch-generated volume `/store-frontend/src/store-frontend-broken-instrumented` so the compose file `deploy/docker-compose/docker-compose-broken-instrumented.yml` will work OOTB

Remove compose volume

---

attackbox/Dockerfile
store-frontend/src/store-frontend-initial-state/config/environments/development.rb

We received a report that the frontend image was erroring out on M1 Macs. There is a simple workaround by commenting out a config line in `development.rb`. I tested locally via `docker-compose-local.yml` and the app spins up as expected, and changes are still propagated via the mounted volume.
Separately, when trying to test this locally, I discovered that the base image for attackbox now gives a 404. I've updated it, along with the hydra package, so it should build properly 
https://datadoghq.atlassian.net/browse/WEB-2593

Add M1 mac fix, update attackbox base image

---

README.md

Links to images in the README are still pointing to the `master` branch. This is OK for older ones that were already there before the move, but not for the new ones.
This fixes all links to point to `main` instead.

Fix links to images in the README

---

discounts-service-fixed/discounts.py

As part of this PR: https://github.com/DataDog/ecommerce-workshop/pull/197  it was removed the line that fixes the n+1 query in the discounts-fixed version of discounts. So both the broken version and the fixed versions had the same issue.
This PR re-adds the fix so those two images are different.

fix n+1 query in discounts-fixed
