README.md

Minor nit, but it's good to keep things tidy. :)

fix path to docker-compose-files

---

README.md
k8s-manifests/ecommerce-app/frontend.yaml

Improve our K8s manifests so that RUM is also enabled there

Enable RUM for K8s as well

---

docker-compose-files/docker-compose-broken-no-apm-instrumentation.yml

added docker compose with no apm,logs instrumentation for new intro to apm course

added docker compose with no apm,logs instrumentation

---

docker-compose-files/docker-compose-broken-instrumented.yml
docker-compose-files/docker-compose-broken-no-apm-instrumentation.yml

Added the lines based on the other docker-compose files I have.

added volumes for frontend, discounts, ads services

---

store-frontend-broken-instrumented/frontend/app/views/spree/layouts/spree_application.html.erb
store-frontend-broken-instrumented/frontend/app/views/spree/orders/edit.html.erb
store-frontend-broken-instrumented/store-frontend/app/views/layouts/application.html.erb
store-frontend-broken-instrumented/store-frontend/app/views/spree/layouts/spree_application.html.erb
store-frontend-broken-instrumented/store-frontend/app/views/spree/orders/edit.html.erb
store-frontend-broken-no-instrumentation/frontend/app/views/spree/orders/edit.html.erb
store-frontend-broken-no-instrumentation/store-frontend/app/views/spree/orders/edit.html.erb
store-frontend-instrumented-fixed/frontend/app/views/spree/layouts/spree_application.html.erb
store-frontend-instrumented-fixed/frontend/app/views/spree/orders/edit.html.erb
store-frontend-instrumented-fixed/store-frontend/app/views/layouts/application.html.erb
store-frontend-instrumented-fixed/store-frontend/app/views/spree/layouts/spree_application.html.erb
store-frontend-instrumented-fixed/store-frontend/app/views/spree/orders/edit.html.erb

- add RUM global context and user action on checkout
- add service, env, version to RUM init
- add a JS error trying to access `window.locatoin`

Add more RUM

---

ads-service/ads.py
discounts-service-fixed/discounts.py

Wraps quickly the python call to the DB to avoid big propagation of stack trace

Wrapping call to catch error properly

---

deploy/aws/ecs/shop-task.json
deploy/docker-compose/docker-compose-broken-instrumented.yml
deploy/docker-compose/docker-compose-fixed-instrumented-livecode.yml
deploy/docker-compose/docker-compose-fixed-instrumented.yml
deploy/gcp/gke/advertisements.yaml
deploy/gcp/gke/discounts.yaml
deploy/generic-k8s/ecommerce-app/advertisements.yaml
deploy/generic-k8s/ecommerce-app/discounts.yaml
deploy/openshift/ecommerce-app/advertisements.yaml
deploy/openshift/ecommerce-app/discounts.yaml

Enable python continuous profiler in the ads and discounts services.

Enable profiling

---

.github/workflows/discounts-fixed.yml
.github/workflows/discounts.yml

Similar to #49 and #66 this uses github actions to build and publish docker containers for the discounts service to help automate updates in the future. I have already created the relevant repositories in Dockerhub.

Github actions workflows for Discounts service builds

---

README.md
traffic-replay/Dockerfile
traffic-replay/requests_0.gor

This is a container definition that automatically does traffic replay.
Target can be specified by ENV to support things like load balancers / proxy

Add traffic-replay container

---

.github/workflows/storefront-fixed.yml
.github/workflows/storefront.yml

This is the last piece of the puzzle for the service workflows to automate and ship their builds to Dockerhub

Create github workflows for the storefront

---

deploy/docker-compose/docker-compose-broken-instrumented.yml
deploy/docker-compose/docker-compose-broken-no-apm-instrumentation.yml
deploy/docker-compose/docker-compose-broken-no-instrumentation.yml
deploy/docker-compose/docker-compose-fixed-instrumented-livecode.yml
deploy/docker-compose/docker-compose-fixed-instrumented.yml

These were out of date in terms of the datadog agent version, folder locations, and image names. We can stamp a 1.0 on everything once we get these all verified as working with our various scenarios.

Cleanup and update docker-compose scripts

---

.github/workflows/advertisements-fixed.yml
.github/workflows/advertisements.yml
.github/workflows/discounts-fixed.yml
.github/workflows/discounts.yml
.github/workflows/storefront-fixed.yml
.github/workflows/storefront.yml

In support of #84 this updates all the workflows to use main over master

Update Github Actions Workflows with new default branch

---

CHANGELOG.md

It's a lot of stuff, but we'll track it better in the future. Wanted to get this going now so we can update it when we drop 1.0.

Start documenting changes between releases

---

deploy/terraform/aws-ec2/.gitignore
deploy/terraform/aws-ec2/README.md
deploy/terraform/aws-ec2/install_advertisements_host.sh.tpl
deploy/terraform/aws-ec2/install_db_host.sh.tpl
deploy/terraform/aws-ec2/install_discounts_host.sh.tpl
deploy/terraform/aws-ec2/install_frontend_host.sh.tpl
deploy/terraform/aws-ec2/main.tf
deploy/terraform/aws-ec2/network.tf
deploy/terraform/aws-ec2/outputs.tf
deploy/terraform/aws-ec2/runshtemplate
deploy/terraform/aws-ec2/setuphosts.sh
deploy/terraform/aws-ec2/variables.tf

Why would I want to do this? Because for the Monitoring Kubernetes Workloads course, I migrate from a traditional setup to Kubernetes. So I need this running in EC2.

Be able to deploy the application to AWS EC2 without kubernetes or docker

---

deploy/generic-k8s/ecommerce-app/advertisements.yaml
deploy/generic-k8s/ecommerce-app/discounts.yaml
deploy/generic-k8s/ecommerce-app/frontend.yaml

These are the older image names and not the updated ones from the 1.0 release.
Fixes #129

Fixup image names for generic k8s manifests

---

.github/workflows/attackbox.yml
.github/workflows/release.yml
deploy/docker-compose/docker-compose-fixed-instrumented-attack.yml

This adds Github workflows for the new attackbox container so the image can be pushed to Dockerhub

Add workflows for attackbox

---

README.md
deploy/docker-compose/README.md

Nothing extraordinary, just a small typo and a doc fix.

(Doc) Small typo and documentation fix

---

deploy/docker-compose/docker-compose-fixed-instrumented-attack.yml
deploy/docker-compose/docker-compose-local-baseline.yml

Use `2.1.3` images for attackbox updates

Update compose files for new attackbox updates

---

ads-service-fixed/Dockerfile
ads-service/Dockerfile
discounts-service-fixed/Dockerfile
discounts-service/Dockerfile

Suppressing this tag from showing up in our 101 courses is awkward at best :)

remove hardcoded DD_ENV=development

---

Makefile
ads-service-fixed/ads.py
ads-service-fixed/requirements.txt
ads-service/ads.py
ads-service/requirements.txt
discounts-service-fixed/discounts.py
discounts-service-fixed/requirements.txt
discounts-service/discounts.py
discounts-service/requirements.txt

- Adding CORS to discounts and ads #187  
- Updating dd-trace #195 
**How to test**
1. Pull down locally
2. Run `DD_API_KEY=[key] make local-baseline-start` to start the app
3. Open localhost:3000
4. Click through the site
5. Verify in DD APM that traces are coming through as expected
To verify that discounts and ads can be retrieved async, updates to the storefront are required: https://github.com/DataDog/LearningLabs/blob/main/snippets/rumcwv/assets/spree_application.html.erb#L58

Add CORS to discounts and ads service

---

.github/workflows/release.yml

This adds the new `discounts-react-app` to the `release` github workflow

Add discounts-react-app to release

---

deploy/launchdarklywebinar/ecommerce-v2/frontend_weighted.yaml
store-frontend/src/store-frontend-weighted/Gemfile
store-frontend/src/store-frontend-weighted/app/controllers/spree/home_controller.rb
store-frontend/src/store-frontend-weighted/config/initializers/launchdarkly.rb
store-frontend/src/store-frontend-weighted/config/puma.rb

Adding in LaunchDarkly Feature Flag for usage

Add in feature flag

---

ads-service-versions/ads_versions/ads_2_1.py

For Ads 2.1 add in same flag as 2.0

Fix LD Flag Logic
